### ISSUE TITLE
Fix bug on line 1244 of "01_kinematics.tex" in "Saveliev_physics_general_Vol_1"

### ISSUE THREAD

**Issue by nguyenthanhlong28032003** [lnacquaroli/LaTeXOldBooks#1]
I fix that code to be:
`Uniform circular motion can be characterized by the \textbf{period of revolution} $T$. It is defined as the time  during which a body completes one revolution, i.e. rotates through the angle $2\pi \si{rad}$, or $\SI{360}{^{\circ}}$. Since the time interval $\Delta t=T$ corresponds to the angle of rotation $\Delta\varphi=2\pi$, we have`

 In your file, you wrote "\SI{2\pi}{\radian}" and my computer can't complie it, so I let "\pi" outside the \SI{}.

**Comment by nguyenthanhlong28032003** [comment]
> "Uniform circular motion can be characterized by the \textbf{period of revolution} T. It is defined as the time during which a body completes one revolution, i.e. rotates through the angle 2π\sirad, or \SI360∘. Since the time interval Δt=T corresponds to the angle of rotation Δφ=2π, we have"
> 
> In your file, you wrote "\SI{2\pi}{\radian}" and my computer can't complie it, so I let "\pi" outside the \SI{}.

**Comment by lnacquaroli** [comment]
Is it related to your lack of the [SIunitx](https://ctan.org/pkg/siunitx) package?

**Comment by lnacquaroli** [comment]
Consider all the other issues closed having the same problem. Make sure you either have the packages I used or change the files locally.
