### ISSUE TITLE
Missing picture in ch_17 of saveliev_physics_general_course_2

### ISSUE THREAD

**Issue by nguyenthanhlong28032003** [lnacquaroli/LaTeXOldBooks#4]

**Comment by lnacquaroli** [comment]
You will have to be more specific about which picture. I cannot spot it inside the pdf.

**Comment by lnacquaroli** [comment]
You meant inside the folders... Will do that soon. Thanks!

**Comment by lnacquaroli** [comment]
Done https://github.com/lnacquaroli/LaTeXOldBooks/commit/ce4ff07ed93ebd7aa0acc6b8ea465c7862be981c
